import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home({title}) {
  return (
    <>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav>
          <img src="" alt="" />
          <a href="/"><img src="" alt="" /><h2>Home</h2></a>
          <a href="/events"><img src="" alt="" /> <h2>Events</h2></a>
          <a href="/about-us"><img src="" alt="" /><h2> About-Us</h2></a>
        </nav>
      </header>
      
      <main className={styles.main}>
        <a href='/events/london'>
          <h2>Events in london</h2>
          <p>Lorem ipsum</p>
         </a>

         <a href='/events/SanFransisco'>
          <h2>Events in San Francisco</h2>
          <p>Lorem ipsum</p>
         </a>

         <a href='/events/barcelona'>
          <h2>Events in Barcelona</h2>
          <p>Lorem ipsum</p>
         </a>
       </main>

      
      
        <footer className={styles.footer}>
      <p> 2022 Next Js - React - Vercel Deployment by David Gonzalez learned from free code camp / time to code</p>
        </footer>
    </>
  )
}
export function getServerSideProps(){
  return {
      props:{
          title: 'Events'

      }
  }
}